version: '3'

services:
  web:
    build: ./Docker/
    command: bash -c "pip install -r requirements.txt && cd ceresia_web_app && python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    container_name: ceresia_app
    volumes:
      - .:/ceresia_app
    ports:
      - "8000:8000"