# Generated by Django 3.2.9 on 2021-11-07 17:17

from django.db import migrations
import django_bleach.models


class Migration(migrations.Migration):

    dependencies = [
        ('Ceresia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hike',
            name='duration',
            field=django_bleach.models.BleachField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='hike',
            name='rating',
            field=django_bleach.models.BleachField(max_length=150, null=True),
        ),
    ]
