# Generated by Django 3.2.9 on 2021-11-07 17:41

from django.db import migrations
import django_bleach.models


class Migration(migrations.Migration):

    dependencies = [
        ('Ceresia', '0002_auto_20211107_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='species',
            name='name',
            field=django_bleach.models.BleachField(max_length=150, null=True),
        ),
    ]
