# Generated by Django 3.2.9 on 2021-11-07 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ceresia', '0003_alter_species_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='species',
            name='name',
        ),
    ]
